"""
-------------------------------------------------------------------------------
File: visualizations.py
Author: Aaron Noah Horvitz
Last Revision Date: 6/10/2024

Description:
-----------
This visualizations file is part of the TopicMiner project, aimed at processing
and analyzing Outlook emails saved as .txt files. It includes functions to
visualize data using the pre-packaged pyLDAvis library. The visualizations help
in understanding the distribution and relationship of topics within the email data.
These scripts are executed within a Jupyter Notebook environment to leverage
interactive visualization capabilities.

Key Functions:
- make_lda_viz: Executes the pyLDAvis visualization in a Jupyter Notebook, providing
  an interactive interface to explore the topics modeled by LDA.

Usage:
-----
This script is intended to be used within a Jupyter Notebook to benefit from the
interactive widgets and immediate display of processed results. Ensure that the
Jupyter Notebook has access to the required Python modules and the TopicMiner
utilities.

-------------------------------------------------------------------------------
"""

# Standard library imports
import pandas as pd

# Machine learning and topic modeling
import pyLDAvis.gensim_models as gensimvis
from topicminer.utils import prepare_corpus_and_dictionary
from gensim.models import LdaModel 


def make_lda_viz( 
        lda_model_tfidf,
        ):
    """
    Produces the pyLDAvis visualization in a Jupyter Notebook, facilitating the exploration
    of topics extracted via LDA models.

    Parameters:
    ----------
    df_emails : pd.DataFrame
        DataFrame containing the documents to be categorized, where each row represents a document.
    processed_text_col : str, optional
        The name of the column in 'df_emails' that contains the preprocessed text suitable for topic modeling.
    lda_model_tfidf : LdaMulticore Object
        The trained LDA model from which the visualization is generated.

    Returns:
    -------
    lda_visualization : pyLDAvis._prepare.PreparedData
        An interactive PyLDAvis visualization object ready to be displayed in a Jupyter Notebook.

    Examples:
    --------
    >>> df_emails = pd.DataFrame({'processed_text': ["text about health", "text about finance"]})
    >>> lda_model = train_some_lda_model(df_emails['processed_text'])
    >>> lda_viz = make_lda_viz(df_emails, lda_model, 'processed_text')
    >>> pyLDAvis.display(lda_viz)

    Note:
    -----
    Ensure the lda_model_tfidf is properly trained and the DataFrame contains the specified column with
    preprocessed text data.
    """
    # Prepare the dictionary and corpus from the DataFrame using the specified utility function
    dictionary, corpus = prepare_corpus_and_dictionary()

    # Create pyLDAvis object for display
    lda_visualization = gensimvis.prepare(
        lda_model_tfidf, corpus, dictionary, sort_topics=False
        )

    return lda_visualization

def display_topic_words(lda_model: LdaModel, num_words: int = 10) -> pd.DataFrame:
    """
    Extracts the top words for each topic from an LDA model and formats them into a DataFrame.

    Parameters
    ----------
    lda_model : LdaModel
        The trained LDA model from which to extract the topic words.
    num_words : int, optional
        The number of top words to retrieve for each topic, default is 10.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing two columns: 'Category' which lists the topic IDs and 'Key Terms'
        which lists the top words associated with each topic.

    Examples
    --------
    >>> from gensim.models import LdaModel
    >>> lda_model = LdaModel(corpus, num_topics=5, id2word=dictionary, passes=15)
    >>> topics_df = display_topic_words(lda_model, num_words=10)
    >>> print(topics_df)

    Notes
    -----
    The function iterates through each topic generated by the LDA model, retrieving the top words
    according to their probability of association with the topic. These words are then formatted into
    a string and combined with the topic ID in a pandas DataFrame for easy viewing or further analysis.
    """

    def extract_topic_string(words):
        """Helper function to convert topic words and probabilities into a formatted string."""
        topic_str = ", ".join([word for word, _ in words])

        topic_str = ""
        for topic, prob in words:
            topic_str += f" ,{topic}"
        topic_str = topic_str.lstrip(" ,")
        return topic_str

    topic_id_list = []
    topic_string_list = []

    for topic_id in range(lda_model.num_topics):

        words = lda_model.show_topic(topicid=topic_id, topn=num_words)
        topic_str = extract_topic_string(words)

        topic_id_list.append(topic_id)
        topic_string_list.append(topic_str)

    lda_terms_df = pd.DataFrame(
        {"Category": topic_id_list, "Key Terms": topic_string_list}
    )
    return lda_terms_df

